name: CI Setup
description: Setup Node.js and install dependencies
inputs:
  root-path:
    description: 'Path of the project'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Set yarn lock path
      id: yarn-hash
      shell: bash
      run: |
        echo "Root path: ${{ inputs.root-path }}"
        echo "yarn.lock path: ${{ inputs.root-path }}/yarn.lock"
        echo "File exists: $(test -f "${{ inputs.root-path }}/yarn.lock" && echo "yes" || echo "no")"
        echo "yarnlock_path=${{ inputs.root-path }}/yarn.lock" >> "$GITHUB_ENV"

    - name: Cache dependencies
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ inputs.root-path }}/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles(env.yarnlock_path) }}

    - name: Install dependencies
      shell: bash
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.root-path }}
        yarn install --immutable
