name: CI Setup
description: Setup Node.js and install dependencies
inputs:
  root-path:
    description: 'Path of the project'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ inputs.root-path }}
        yarn install --immutable
