name: CI Setup
description: Setup Node.js and install dependencies
inputs:
  root-path:
    description: 'Path of the project'
    required: true
  package-manager:
    description: 'Package manager of the project'
    required: false
    default: 'yarn'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: ${{ inputs.package-manager }}
        cache-dependency-path: ${{ inputs.root-path }}/${{ inputs.package-manager }}.lock

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ inputs.root-path }}
        if [ "${{ inputs.package-manager }}" = "npm" ]; then
          npm ci
        else
          yarn install --immutable
        fi
