// Parses the terminal setup QR generated by the merchant dashboard's API key
// reveal dialog. The QR encodes a deep link:
//
//   wpay://setup?apiKey=<customer api key>&merchantId=<merchant id>
//
// It's a deep link (not plain JSON) so a phone camera offers to open the app
// instead of sending the secret to a web search. The same link reaches the app
// two ways: scanned in-app (`app/scan-setup-qr.tsx`) or opened by the OS
// (`app/setup.tsx`). The dashboard and both app variants use `wpay://`; suffixed
// schemes remain accepted here so an in-app scan also tolerates older QR links.

export interface SetupPayload {
  merchantId: string;
  apiKey: string;
}

const SETUP_LINK_PATTERN = /^wpay(?:-[a-z0-9]+)?:\/\/setup\/?(?:\?(.*))?$/i;

// Values may arrive as arrays when a query param is repeated (expo-router
// search params); only a single non-empty value is accepted.
type ParamValue = string | string[] | undefined | null;

function toValue(value: ParamValue): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

export function toSetupPayload(
  apiKey: ParamValue,
  merchantId: ParamValue,
): SetupPayload | null {
  const key = toValue(apiKey);
  const id = toValue(merchantId);
  return key && id ? { apiKey: key, merchantId: id } : null;
}

export function parseSetupQr(raw: string): SetupPayload | null {
  const match = SETUP_LINK_PATTERN.exec(raw.trim());
  if (!match) return null;
  try {
    const params = new URLSearchParams(match[1] ?? "");
    return toSetupPayload(params.get("apiKey"), params.get("merchantId"));
  } catch {
    // React Native's URLSearchParams throws on malformed percent-encoding.
    return null;
  }
}
