#!/bin/bash
# Script that copies mock files to the correct location (skips if file exists)

copy_if_missing() {
    local src="$1"
    local dest="$2"
    if [ ! -f "$src" ]; then
        echo "Skipped (source not found): $src"
        return
    fi
    if [ -f "$dest" ]; then
        echo "Skipped (exists): $dest"
        return
    fi
    cp "$src" "$dest"
    echo "Copied: $dest"
}

# android/ is generated by `expo prebuild` (Continuous Native Generation), so
# the debug keystore comes from the Expo template and android/secrets.properties
# is seeded by scripts/setup-secrets.js (postprebuild). Here we only seed .env.
copy_if_missing .env.example .env
