// Expo config plugin: reproduces the wallet's Android build variants in the
// prebuild-generated android/app/build.gradle, so the existing CI (and the
// shared release-android-base workflow) keeps working unchanged:
//
//   ./gradlew assembleRelease   -> production  (com.walletconnect.web3wallet.rnsample)
//   ./gradlew assembleInternal  -> internal    (...rnsample.internal)
//
// It loads credentials from android/secrets.properties and adds:
//   - signingConfigs.internal (WC_*_INTERNAL) and signingConfigs.release (WC_*_UPLOAD)
//   - an `internal` buildType (.internal applicationId + -internal versionName,
//     internal signing, matchingFallbacks release)
//   - points the `release` buildType at signingConfigs.release
//
// (debug stays on Expo's default debug keystore. iOS variants are handled by
// APP_VARIANT in app.config.js instead — Android uses buildTypes to match CI.)
//
// It also writes a buildType manifest overlay (android/app/src/internal/
// AndroidManifest.xml) registering the internal deep-link scheme. This CAN'T
// come from app.config.js's top-level `scheme` (that only reflects APP_VARIANT
// at prebuild time): CI prebuilds Android once as production and derives the
// .internal build purely from the Gradle buildType, so without this overlay the
// internal APK advertises rn-web3wallet-internal:// (see src/utils/misc.ts) but
// only registers rn-web3wallet:// — and deep-link-back doesn't open the wallet.
// Mirrors the old bare-RN android/app/src/internal/AndroidManifest.xml.
const path = require('path');
const fs = require('fs');
const { withAppBuildGradle, withDangerousMod } = require('@expo/config-plugins');

// Deep-link config for the `internal` buildType (see src/utils/misc.ts
// ENV_CONFIG.internal). Written as a buildType manifest overlay so it only lands
// in assembleInternal, never in production/release.
const INTERNAL_SCHEME = 'rn-web3wallet-internal';
const INTERNAL_LINK_PATH = '/rn_walletkit_internal';
const APP_LINK_HOSTS = ['appkit-lab.reown.com', 'lab.reown.com'];

function internalManifest() {
  const appLinkData = APP_LINK_HOSTS.map(
    host =>
      `                <data android:scheme="https" android:host="${host}" android:pathPrefix="${INTERNAL_LINK_PATH}"/>`,
  ).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidVariants.js. Merged into assembleInternal
     only. Registers the ${INTERNAL_SCHEME} deep-link scheme (+ ${INTERNAL_LINK_PATH}
     App Links) that the internal build advertises to WalletConnect. Don't edit. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application>
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="${INTERNAL_SCHEME}"/>
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
${appLinkData}
            </intent-filter>
        </activity>
    </application>
</manifest>
`;
}

function addAndroidVariants(buildGradle) {
  // Idempotent — prebuild regenerates build.gradle, but guard double application.
  if (buildGradle.includes('def secretsProperties = new Properties()')) {
    return buildGradle;
  }

  // 1. Load secrets.properties before the signingConfigs block.
  const loadSecrets = `
    def secretsProperties = new Properties()
    def secretsPropertiesFile = rootProject.file("secrets.properties")
    if (secretsPropertiesFile.exists()) {
        secretsProperties.load(new FileInputStream(secretsPropertiesFile))
    }

    `;
  buildGradle = buildGradle.replace(
    /(\n\s*signingConfigs\s*\{)/,
    `${loadSecrets}$1`,
  );

  // 2. Add internal + release signing configs after the default `debug` one.
  const signingConfigs = `        internal {
            if (secretsPropertiesFile.exists()) {
                storeFile file(secretsProperties['WC_FILENAME_INTERNAL'])
                storePassword secretsProperties['WC_STORE_PASSWORD_INTERNAL']
                keyAlias secretsProperties['WC_KEYSTORE_ALIAS']
                keyPassword secretsProperties['WC_KEY_PASSWORD_INTERNAL']
            }
        }
        release {
            if (secretsPropertiesFile.exists()) {
                storeFile file(secretsProperties['WC_FILENAME_UPLOAD'])
                storePassword secretsProperties['WC_STORE_PASSWORD_UPLOAD']
                keyAlias secretsProperties['WC_KEYSTORE_ALIAS']
                keyPassword secretsProperties['WC_KEY_PASSWORD_UPLOAD']
            }
        }`;
  buildGradle = buildGradle.replace(
    /(signingConfigs\s*\{[^}]*debug\s*\{[^}]*\})\s*(\n\s*\})/s,
    `$1\n${signingConfigs}\n    $2`,
  );

  // 3. Add the `internal` buildType at the top of the buildTypes block.
  const internalBuildType = `        internal {
            applicationIdSuffix ".internal"
            versionNameSuffix "-internal"
            signingConfig signingConfigs.internal
            matchingFallbacks = ['release']
        }`;
  buildGradle = buildGradle.replace(
    /(\n\s*buildTypes\s*\{)/,
    `$1\n${internalBuildType}`,
  );

  // 4. Point the release buildType at signingConfigs.release (Expo defaults to .debug).
  buildGradle = buildGradle.replace(
    /(release\s*\{[^}]*?)signingConfig\s+signingConfigs\.debug/s,
    '$1signingConfig signingConfigs.release',
  );

  // 5. Give the debug buildType a .debug applicationId so it can coexist with
  // release + internal (Expo's default debug has no suffix → collides with
  // release). `signingConfig signingConfigs.debug` is unique to this block.
  buildGradle = buildGradle.replace(
    /(\n(\s*)signingConfig\s+signingConfigs\.debug\b)/,
    '\n$2applicationIdSuffix ".debug"\n$2versionNameSuffix "-debug"$1',
  );

  return buildGradle;
}

const withInternalSchemeManifest = config =>
  withDangerousMod(config, [
    'android',
    cfg => {
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'internal',
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'AndroidManifest.xml'), internalManifest());
      return cfg;
    },
  ]);

const withAndroidVariants = config => {
  config = withAppBuildGradle(config, cfg => {
    if (cfg.modResults.language === 'groovy') {
      cfg.modResults.contents = addAndroidVariants(cfg.modResults.contents);
    }
    return cfg;
  });
  config = withInternalSchemeManifest(config);
  return config;
};

module.exports = withAndroidVariants;
// Exported for unit testing the transform in isolation.
module.exports.addAndroidVariants = addAndroidVariants;
module.exports.internalManifest = internalManifest;
