name: 'Install Maestro'
description: 'Install latest Maestro version'

runs:
  using: 'composite'
  steps:
    - name: 'Install Maestro'
      shell: bash
      run: |
        curl -Ls "https://get.maestro.mobile.dev" | bash
        export PATH="$PATH":"$HOME/.maestro/bin"
        echo "$HOME/.maestro/bin" >> $GITHUB_PATH
        maestro --version