import { Chain } from '@/utils/types';

// Helpers
export const EIP155_CHAINS: Record<string, Chain> = {
  'eip155:1': {
    chainId: '1',
    namespace: 'eip155',
    name: 'Ethereum',
    rpcUrl: 'https://eth.llamarpc.com',
    icon: require('@/assets/chains/ethereum.webp'),
  },
  'eip155:5': {
    chainId: '5',
    namespace: 'eip155',
    name: 'Ethereum Goerli',
    rpcUrl: 'https://rpc.ankr.com/eth_goerli',
    icon: require('@/assets/chains/ethereum.webp'),
  },
  'eip155:42161': {
    chainId: '42161',
    namespace: 'eip155',
    name: 'Arbitrum One',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    icon: require('@/assets/chains/arbitrum.webp'),
  },
  'eip155:43114': {
    chainId: '43114',
    namespace: 'eip155',
    name: 'Avalanche',
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    icon: require('@/assets/chains/avalanche.webp'),
  },
  'eip155:43113': {
    chainId: '43113',
    namespace: 'eip155',
    name: 'Avalanche Fuji',
    rpcUrl: 'https://api.avax-test.network/ext/bc/C/rpc',
    icon: require('@/assets/chains/avalanche.webp'),
  },
  'eip155:56': {
    chainId: '56',
    namespace: 'eip155',
    name: 'Binance Smart Chain',
    rpcUrl: 'https://rpc.ankr.com/bsc',
    icon: require('@/assets/chains/binance.webp'),
  },
  'eip155:250': {
    chainId: '250',
    namespace: 'eip155',
    name: 'Fantom',
    rpcUrl: 'https://rpc.ankr.com/fantom',
    icon: require('@/assets/chains/fantom.webp'),
  },
  'eip155:10': {
    chainId: '10',
    namespace: 'eip155',
    name: 'Optimism',
    rpcUrl: 'https://mainnet.optimism.io',
    icon: require('@/assets/chains/optimism.webp'),
  },
  'eip155:11155420': {
    chainId: '11155420',
    namespace: 'eip155',
    name: 'Optimism Sepholia',
    rpcUrl: 'https://sepolia.optimism.io',
    icon: require('@/assets/chains/optimism.webp'),
  },
  'eip155:137': {
    chainId: '137',
    namespace: 'eip155',
    name: 'Polygon',
    rpcUrl: 'https://polygon-rpc.com',
    icon: require('@/assets/chains/polygon.webp'),
  },
  'eip155:80001': {
    chainId: '80001',
    namespace: 'eip155',
    name: 'Polygon Mumbai',
    rpcUrl: 'https://rpc.ankr.com/polygon_mumbai',
    icon: require('@/assets/chains/polygon.webp'),
  },
  'eip155:100': {
    chainId: '100',
    namespace: 'eip155',
    name: 'Gnosis',
    rpcUrl: 'https://rpc.gnosischain.com',
    icon: require('@/assets/chains/gnosis.webp'),
  },
  'eip155:9001': {
    chainId: '9001',
    namespace: 'eip155',
    name: 'Evmos',
    rpcUrl: 'https://eth.bd.evmos.org:8545',
    icon: require('@/assets/chains/evmos.webp'),
  },
  'eip155:324': {
    chainId: '324',
    namespace: 'eip155',
    name: 'zkSync Era',
    rpcUrl: 'https://mainnet.era.zksync.io',
    icon: require('@/assets/chains/zksync.webp'),
  },
  'eip155:314': {
    chainId: '314',
    namespace: 'eip155',
    name: 'Filecoin Mainnet',
    rpcUrl: 'https://api.node.glif.io/rpc/v1',
    icon: require('@/assets/chains/filecoin.webp'),
  },
  'eip155:4689': {
    chainId: '4689',
    namespace: 'eip155',
    name: 'IoTeX',
    rpcUrl: 'https://babel-api.mainnet.iotex.io',
    icon: require('@/assets/chains/iotx.webp'),
  },
  'eip155:1088': {
    chainId: '1088',
    namespace: 'eip155',
    name: 'Metis',
    rpcUrl: 'https://andromeda.metis.io/?owner=1088',
    icon: require('@/assets/chains/metis.webp'),
  },
  'eip155:1284': {
    chainId: '1284',
    namespace: 'eip155',
    name: 'Moonbeam',
    rpcUrl: 'https://moonbeam.public.blastapi.io',
    icon: require('@/assets/chains/moonbeam.webp'),
  },
  'eip155:1285': {
    chainId: '1285',
    namespace: 'eip155',
    name: 'Moonriver',
    rpcUrl: 'https://moonriver.public.blastapi.io',
    icon: require('@/assets/chains/moonriver.webp'),
  },
  'eip155:7777777': {
    chainId: '7777777',
    namespace: 'eip155',
    name: 'Zora',
    rpcUrl: 'https://rpc.zora.energy',
    icon: require('@/assets/chains/zora.webp'),
  },
  'eip155:42220': {
    chainId: '42220',
    namespace: 'eip155',
    name: 'Celo',
    rpcUrl: 'https://forno.celo.org',
    icon: require('@/assets/chains/celo.webp'),
  },
  'eip155:8453': {
    chainId: '8453',
    namespace: 'eip155',
    name: 'Base',
    rpcUrl: 'https://mainnet.base.org',
    icon: require('@/assets/chains/base.webp'),
  },
  'eip155:1313161554': {
    chainId: '1313161554',
    namespace: 'eip155',
    name: 'Aurora',
    rpcUrl: 'https://mainnet.aurora.dev',
    icon: require('@/assets/chains/aurora.webp'),
  },
};

export const EIP155_SIGNING_METHODS = {
  PERSONAL_SIGN: 'personal_sign',
  ETH_SIGN: 'eth_sign',
  ETH_SIGN_TRANSACTION: 'eth_signTransaction',
  ETH_SIGN_TYPED_DATA: 'eth_signTypedData',
  ETH_SIGN_TYPED_DATA_V3: 'eth_signTypedData_v3',
  ETH_SIGN_TYPED_DATA_V4: 'eth_signTypedData_v4',
  ETH_SEND_RAW_TRANSACTION: 'eth_sendRawTransaction',
  ETH_SEND_TRANSACTION: 'eth_sendTransaction',
};
