name: release-ios-walletkit-production

permissions:
  id-token: write
  contents: read

on: 
  workflow_dispatch:
    inputs:
      build-for-simulator:
        description: "Build for simulator instead of App Store"
        required: false
        default: false
        type: boolean

jobs:
  release-production:
    uses: ./.github/workflows/release-ios-base.yaml
    with:
      name: WalletKit React Native
      root-path: 'wallets/rn_cli_wallet'
      xcode-project-path: 'wallets/rn_cli_wallet/ios/RNWeb3Wallet.xcodeproj'
      xcode-workspace-path: 'wallets/rn_cli_wallet/ios/RNWeb3Wallet.xcworkspace'
      release-type: 'production'
      scheme-name: 'RNWallet'
      bundle-id: 'com.walletconnect.web3wallet.rnsample'
      apple-id: '6449264964'
      project-type: 'wallet'
      build-for-simulator: ${{ inputs.build-for-simulator }}
    secrets:
      project-id: ${{ secrets.ENV_WALLET_PROJECT_ID }}
      relay-url: ${{ secrets.ENV_RELAY_URL }}
      sentry-dsn: ${{ secrets.W3W_SENTRY_DSN }}
      sentry-file: ${{ secrets.W3W_SENTRY_FILE }}
      apple-username: ${{ secrets.APPLE_USERNAME }}
      apple-key-id: ${{ secrets.APPLE_KEY_ID }}
      apple-key-content: ${{ secrets.APPLE_KEY_CONTENT }}
      apple-issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
      match-username: ${{ secrets.MATCH_USERNAME }}
      match-keychain-password: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      match-git-url: ${{ secrets.MATCH_GIT_URL }}
      match-ssh-key: ${{ secrets.MATCH_SSH_KEY }}
      google-services-file: ${{ secrets.W3W_IOS_PROD_GOOGLE_SERVICES_FILE }}
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
      testflight-url: ${{ secrets.TESTFLIGHT_WALLETKIT_PROD_URL }}